// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestInfoMsg.proto

package com.skyworth.beehelperserver.protocol;

public final class RequestInfoMsg {
  private RequestInfoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string msgUid = 1;</code>
     */
    boolean hasMsgUid();
    /**
     * <code>required string msgUid = 1;</code>
     */
    java.lang.String getMsgUid();
    /**
     * <code>required string msgUid = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgUidBytes();

    /**
     * <code>required int32 msgType = 2;</code>
     */
    boolean hasMsgType();
    /**
     * <code>required int32 msgType = 2;</code>
     */
    int getMsgType();

    /**
     * <code>required int32 msgAction = 3;</code>
     */
    boolean hasMsgAction();
    /**
     * <code>required int32 msgAction = 3;</code>
     */
    int getMsgAction();

    /**
     * <code>repeated .RequestParam msgParam = 4;</code>
     */
    java.util.List<com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam> 
        getMsgParamList();
    /**
     * <code>repeated .RequestParam msgParam = 4;</code>
     */
    com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam getMsgParam(int index);
    /**
     * <code>repeated .RequestParam msgParam = 4;</code>
     */
    int getMsgParamCount();
    /**
     * <code>repeated .RequestParam msgParam = 4;</code>
     */
    java.util.List<? extends com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParamOrBuilder> 
        getMsgParamOrBuilderList();
    /**
     * <code>repeated .RequestParam msgParam = 4;</code>
     */
    com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParamOrBuilder getMsgParamOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code RequestInfo}
   */
  public static final class RequestInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RequestInfo)
      RequestInfoOrBuilder {
    // Use RequestInfo.newBuilder() to construct.
    private RequestInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestInfo defaultInstance;
    public static RequestInfo getDefaultInstance() {
      return defaultInstance;
    }

    public RequestInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              msgUid_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              msgType_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgAction_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                msgParam_ = new java.util.ArrayList<com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam>();
                mutable_bitField0_ |= 0x00000008;
              }
              msgParam_.add(input.readMessage(com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          msgParam_ = java.util.Collections.unmodifiableList(msgParam_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skyworth.beehelperserver.protocol.RequestInfoMsg.internal_static_RequestInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skyworth.beehelperserver.protocol.RequestInfoMsg.internal_static_RequestInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo.class, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<RequestInfo> PARSER =
        new com.google.protobuf.AbstractParser<RequestInfo>() {
      public RequestInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RequestInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MSGUID_FIELD_NUMBER = 1;
    private java.lang.Object msgUid_;
    /**
     * <code>required string msgUid = 1;</code>
     */
    public boolean hasMsgUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string msgUid = 1;</code>
     */
    public java.lang.String getMsgUid() {
      java.lang.Object ref = msgUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgUid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msgUid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgUidBytes() {
      java.lang.Object ref = msgUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGTYPE_FIELD_NUMBER = 2;
    private int msgType_;
    /**
     * <code>required int32 msgType = 2;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 msgType = 2;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int MSGACTION_FIELD_NUMBER = 3;
    private int msgAction_;
    /**
     * <code>required int32 msgAction = 3;</code>
     */
    public boolean hasMsgAction() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 msgAction = 3;</code>
     */
    public int getMsgAction() {
      return msgAction_;
    }

    public static final int MSGPARAM_FIELD_NUMBER = 4;
    private java.util.List<com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam> msgParam_;
    /**
     * <code>repeated .RequestParam msgParam = 4;</code>
     */
    public java.util.List<com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam> getMsgParamList() {
      return msgParam_;
    }
    /**
     * <code>repeated .RequestParam msgParam = 4;</code>
     */
    public java.util.List<? extends com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParamOrBuilder> 
        getMsgParamOrBuilderList() {
      return msgParam_;
    }
    /**
     * <code>repeated .RequestParam msgParam = 4;</code>
     */
    public int getMsgParamCount() {
      return msgParam_.size();
    }
    /**
     * <code>repeated .RequestParam msgParam = 4;</code>
     */
    public com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam getMsgParam(int index) {
      return msgParam_.get(index);
    }
    /**
     * <code>repeated .RequestParam msgParam = 4;</code>
     */
    public com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParamOrBuilder getMsgParamOrBuilder(
        int index) {
      return msgParam_.get(index);
    }

    private void initFields() {
      msgUid_ = "";
      msgType_ = 0;
      msgAction_ = 0;
      msgParam_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMsgParamCount(); i++) {
        if (!getMsgParam(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgUidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, msgType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, msgAction_);
      }
      for (int i = 0; i < msgParam_.size(); i++) {
        output.writeMessage(4, msgParam_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgUidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, msgType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, msgAction_);
      }
      for (int i = 0; i < msgParam_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, msgParam_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestInfo)
        com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.skyworth.beehelperserver.protocol.RequestInfoMsg.internal_static_RequestInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.skyworth.beehelperserver.protocol.RequestInfoMsg.internal_static_RequestInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo.class, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo.Builder.class);
      }

      // Construct using com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMsgParamFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgUid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        msgAction_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (msgParamBuilder_ == null) {
          msgParam_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          msgParamBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.skyworth.beehelperserver.protocol.RequestInfoMsg.internal_static_RequestInfo_descriptor;
      }

      public com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo getDefaultInstanceForType() {
        return com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo.getDefaultInstance();
      }

      public com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo build() {
        com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo buildPartial() {
        com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo result = new com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgUid_ = msgUid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgAction_ = msgAction_;
        if (msgParamBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            msgParam_ = java.util.Collections.unmodifiableList(msgParam_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.msgParam_ = msgParam_;
        } else {
          result.msgParam_ = msgParamBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo) {
          return mergeFrom((com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo other) {
        if (other == com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo.getDefaultInstance()) return this;
        if (other.hasMsgUid()) {
          bitField0_ |= 0x00000001;
          msgUid_ = other.msgUid_;
          onChanged();
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasMsgAction()) {
          setMsgAction(other.getMsgAction());
        }
        if (msgParamBuilder_ == null) {
          if (!other.msgParam_.isEmpty()) {
            if (msgParam_.isEmpty()) {
              msgParam_ = other.msgParam_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureMsgParamIsMutable();
              msgParam_.addAll(other.msgParam_);
            }
            onChanged();
          }
        } else {
          if (!other.msgParam_.isEmpty()) {
            if (msgParamBuilder_.isEmpty()) {
              msgParamBuilder_.dispose();
              msgParamBuilder_ = null;
              msgParam_ = other.msgParam_;
              bitField0_ = (bitField0_ & ~0x00000008);
              msgParamBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMsgParamFieldBuilder() : null;
            } else {
              msgParamBuilder_.addAllMessages(other.msgParam_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgUid()) {
          
          return false;
        }
        if (!hasMsgType()) {
          
          return false;
        }
        if (!hasMsgAction()) {
          
          return false;
        }
        for (int i = 0; i < getMsgParamCount(); i++) {
          if (!getMsgParam(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object msgUid_ = "";
      /**
       * <code>required string msgUid = 1;</code>
       */
      public boolean hasMsgUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string msgUid = 1;</code>
       */
      public java.lang.String getMsgUid() {
        java.lang.Object ref = msgUid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgUid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msgUid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgUidBytes() {
        java.lang.Object ref = msgUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msgUid = 1;</code>
       */
      public Builder setMsgUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msgUid = 1;</code>
       */
      public Builder clearMsgUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgUid_ = getDefaultInstance().getMsgUid();
        onChanged();
        return this;
      }
      /**
       * <code>required string msgUid = 1;</code>
       */
      public Builder setMsgUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgUid_ = value;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <code>required int32 msgType = 2;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 msgType = 2;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>required int32 msgType = 2;</code>
       */
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000002;
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msgType = 2;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private int msgAction_ ;
      /**
       * <code>required int32 msgAction = 3;</code>
       */
      public boolean hasMsgAction() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 msgAction = 3;</code>
       */
      public int getMsgAction() {
        return msgAction_;
      }
      /**
       * <code>required int32 msgAction = 3;</code>
       */
      public Builder setMsgAction(int value) {
        bitField0_ |= 0x00000004;
        msgAction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msgAction = 3;</code>
       */
      public Builder clearMsgAction() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgAction_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam> msgParam_ =
        java.util.Collections.emptyList();
      private void ensureMsgParamIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          msgParam_ = new java.util.ArrayList<com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam>(msgParam_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.Builder, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParamOrBuilder> msgParamBuilder_;

      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public java.util.List<com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam> getMsgParamList() {
        if (msgParamBuilder_ == null) {
          return java.util.Collections.unmodifiableList(msgParam_);
        } else {
          return msgParamBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public int getMsgParamCount() {
        if (msgParamBuilder_ == null) {
          return msgParam_.size();
        } else {
          return msgParamBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam getMsgParam(int index) {
        if (msgParamBuilder_ == null) {
          return msgParam_.get(index);
        } else {
          return msgParamBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public Builder setMsgParam(
          int index, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam value) {
        if (msgParamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgParamIsMutable();
          msgParam_.set(index, value);
          onChanged();
        } else {
          msgParamBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public Builder setMsgParam(
          int index, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.Builder builderForValue) {
        if (msgParamBuilder_ == null) {
          ensureMsgParamIsMutable();
          msgParam_.set(index, builderForValue.build());
          onChanged();
        } else {
          msgParamBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public Builder addMsgParam(com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam value) {
        if (msgParamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgParamIsMutable();
          msgParam_.add(value);
          onChanged();
        } else {
          msgParamBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public Builder addMsgParam(
          int index, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam value) {
        if (msgParamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgParamIsMutable();
          msgParam_.add(index, value);
          onChanged();
        } else {
          msgParamBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public Builder addMsgParam(
          com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.Builder builderForValue) {
        if (msgParamBuilder_ == null) {
          ensureMsgParamIsMutable();
          msgParam_.add(builderForValue.build());
          onChanged();
        } else {
          msgParamBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public Builder addMsgParam(
          int index, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.Builder builderForValue) {
        if (msgParamBuilder_ == null) {
          ensureMsgParamIsMutable();
          msgParam_.add(index, builderForValue.build());
          onChanged();
        } else {
          msgParamBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public Builder addAllMsgParam(
          java.lang.Iterable<? extends com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam> values) {
        if (msgParamBuilder_ == null) {
          ensureMsgParamIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, msgParam_);
          onChanged();
        } else {
          msgParamBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public Builder clearMsgParam() {
        if (msgParamBuilder_ == null) {
          msgParam_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          msgParamBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public Builder removeMsgParam(int index) {
        if (msgParamBuilder_ == null) {
          ensureMsgParamIsMutable();
          msgParam_.remove(index);
          onChanged();
        } else {
          msgParamBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.Builder getMsgParamBuilder(
          int index) {
        return getMsgParamFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParamOrBuilder getMsgParamOrBuilder(
          int index) {
        if (msgParamBuilder_ == null) {
          return msgParam_.get(index);  } else {
          return msgParamBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public java.util.List<? extends com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParamOrBuilder> 
           getMsgParamOrBuilderList() {
        if (msgParamBuilder_ != null) {
          return msgParamBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(msgParam_);
        }
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.Builder addMsgParamBuilder() {
        return getMsgParamFieldBuilder().addBuilder(
            com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.getDefaultInstance());
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.Builder addMsgParamBuilder(
          int index) {
        return getMsgParamFieldBuilder().addBuilder(
            index, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.getDefaultInstance());
      }
      /**
       * <code>repeated .RequestParam msgParam = 4;</code>
       */
      public java.util.List<com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.Builder> 
           getMsgParamBuilderList() {
        return getMsgParamFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.Builder, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParamOrBuilder> 
          getMsgParamFieldBuilder() {
        if (msgParamBuilder_ == null) {
          msgParamBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.Builder, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParamOrBuilder>(
                  msgParam_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          msgParam_ = null;
        }
        return msgParamBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:RequestInfo)
    }

    static {
      defaultInstance = new RequestInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RequestInfo)
  }

  public interface RequestParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestParam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>required string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code RequestParam}
   */
  public static final class RequestParam extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RequestParam)
      RequestParamOrBuilder {
    // Use RequestParam.newBuilder() to construct.
    private RequestParam(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestParam(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestParam defaultInstance;
    public static RequestParam getDefaultInstance() {
      return defaultInstance;
    }

    public RequestParam getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestParam(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skyworth.beehelperserver.protocol.RequestInfoMsg.internal_static_RequestParam_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skyworth.beehelperserver.protocol.RequestInfoMsg.internal_static_RequestParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.class, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.Builder.class);
    }

    public static com.google.protobuf.Parser<RequestParam> PARSER =
        new com.google.protobuf.AbstractParser<RequestParam>() {
      public RequestParam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestParam(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RequestParam> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    /**
     * <code>required string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestParam)
        com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.skyworth.beehelperserver.protocol.RequestInfoMsg.internal_static_RequestParam_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.skyworth.beehelperserver.protocol.RequestInfoMsg.internal_static_RequestParam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.class, com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.Builder.class);
      }

      // Construct using com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.skyworth.beehelperserver.protocol.RequestInfoMsg.internal_static_RequestParam_descriptor;
      }

      public com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam getDefaultInstanceForType() {
        return com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.getDefaultInstance();
      }

      public com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam build() {
        com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam buildPartial() {
        com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam result = new com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam) {
          return mergeFrom((com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam other) {
        if (other == com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.skyworth.beehelperserver.protocol.RequestInfoMsg.RequestParam) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RequestParam)
    }

    static {
      defaultInstance = new RequestParam(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RequestParam)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RequestInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestParam_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RequestParam_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024RequestInfoMsg.proto\"b\n\013RequestInfo\022\016\n" +
      "\006msgUid\030\001 \002(\t\022\017\n\007msgType\030\002 \002(\005\022\021\n\tmsgAct" +
      "ion\030\003 \002(\005\022\037\n\010msgParam\030\004 \003(\0132\r.RequestPar" +
      "am\"*\n\014RequestParam\022\013\n\003key\030\001 \002(\t\022\r\n\005value" +
      "\030\002 \002(\tB7\n%com.skyworth.beehelperserver.p" +
      "rotocolB\016RequestInfoMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RequestInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RequestInfo_descriptor,
        new java.lang.String[] { "MsgUid", "MsgType", "MsgAction", "MsgParam", });
    internal_static_RequestParam_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RequestParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RequestParam_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
